2022/06/02 15:12:29 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:30 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:30 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:31 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:32 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:33 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:33 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:34 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:35 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:35 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:36 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:37 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:37 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:38 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:39 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:39 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:40 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/02 15:12:57 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.30.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:47 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:49 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:50 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:51 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:52 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:53 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:55 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:57 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:59 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:26:59 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:00 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:01 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:01 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:02 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:06 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:07 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:14 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:17 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:28 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:32 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:34 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova-impersonate/users/7/web?redirect_to=/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:34 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:37 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:38 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:39 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:39 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:40 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:41 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:42 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/08 15:27:42 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
2022/06/10 04:08:50 [error] 36#36: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.31.0.5:9000", host: "127.0.0.1"
